import { build } from 'esbuild';
import { readFile, readdir, mkdir, copyFile } from 'node:fs/promises';
import path from 'node:path';

// Cubism 5 SDK for Web R5. Embed the official shaders to avoid extra requests
// and Static Web Apps MIME configuration for .vert/.frag files.
const framework = 'node_modules/cubism-framework';
const shaders = {};
for (const file of await readdir(`${framework}/Shaders/WebGL`)) {
    shaders[file] = await readFile(`${framework}/Shaders/WebGL/${file}`, 'utf8');
}
await build({
    entryPoints: ['src/live2d/runtime.js'],
    outfile: 'Portfolio/wwwroot/js/live2d-runtime.js',
    bundle: true,
    format: 'esm',
    target: 'es2022',
    minify: true,
    legalComments: 'eof',
    banner: { js: '// Generated by npm run build:live2d. Cubism Web Framework 5-r.5 (198a3769). See /lib/live2d/LICENSE.md.' },
    plugins: [{
        name: 'embed-cubism-shaders',
        setup(builder) {
            builder.onLoad({ filter: /cubismshader_webgl\.ts$/ }, async ({ path: file }) => {
                const source = await readFile(file, 'utf8');
                const original = 'const response = await fetch(url);\n    return await response.text();';
                if (!source.includes(original)) throw new Error('Cubism shader loader changed; review the embedding adapter.');
                return {
                    contents: `const embeddedShaders: Record<string, string> = ${JSON.stringify(shaders)};\n` + source.replace(original,
                        "const name = url.split('/').pop();\n    if (!(name in embeddedShaders)) throw new Error('Unknown Cubism shader');\n    return embeddedShaders[name];"),
                    loader: 'ts', resolveDir: path.dirname(file)
                };
            });
        }
    }]
});
await mkdir('Portfolio/wwwroot/lib/live2d', { recursive: true });
await copyFile(`${framework}/LICENSE.md`, 'Portfolio/wwwroot/lib/live2d/LICENSE.md');
